sudo: false
language: node_js
node_js:
  - '0.12'
  - '4.2'
  - '5.0'
before_install: npm install -g grunt-cli yo bower && npm link
install: mkdir testrun && cd testrun &&  yo atomic testProk test TestRunner less true true true && grunt build
before_script: grunt build
script: npm test  

email:
    on_success: never # default: change
    on_failure: change # default: always
