default:
  - serve

serve:
  - clean:server
  - injector
  - wiredep
  - parallelize:jade
  - less:server
  - autoprefixer
  - connect:server
  - watch

build:
  - clean:build
  - injector
  - wiredep
  - parallelize:jade
  - less
  - autoprefixer
  - copy:dist
  - useminPrepare
  - concat
  - combine_mq
  - cssmin
  - uglify
  - imagemin
  - svgmin
  - htmlmin
  - rev
  - usemin

release:
  - bump-only
  - changelog
  - bump-commit

release:patch:
  - bump-only:patch
  - changelog
  - bump-commit

release:minor:
  - bump-only:minor
  - changelog
  - bump-commit

release:major:
  - bump-only:major
  - changelog
  - bump-commit
